### PR TITLE
Issue 21

### LINKED ISSUE #21: Base currency not applied to percentages
On the RECENT PERFORMERS tab, changing the BASE CURRENCY does not affect the percentages displayed. It would be handy if we were able to compare the Recent ROI of a specific project vs ETH's (or BTC's) growth for a specific time period (24 hours, 1 week, 1 month) to see if we would have been better off holding ETH (or BTC) for that time period vs a project's token. It looks like the entire tab just displays that project's ROI in comparison to USD currently? Thanks for your consideration. :)

### PR DESCRIPTION
**Pull request by rongierlach**
Fixes #21 

Needed to add some logic to `src/client/rankings/lib/appendRecentStats` that updated roi data when current currency changed.

### CODE REVIEW

**Comment by coopermaruyama** [comment]
Code looks good - thanks! I will run/test it when I get home and then merge

**Comment by coopermaruyama** [comment]
Works like a charm! 

Only suggestion is to add linter support to your IDE to ensure it passes lint checks. I fixed the lint errors for this one. Merging now - thanks for the help!

**Comment by coopermaruyama** [comment]
This is now live on the site as well

**Comment by rongierlach** [comment]
whoops! looks like I had atom's linter-js-standard package overriding your .eslintrc

**Pull request merged**
